### ISSUE TITLE
Trying to login with CLI and can't

### ISSUE THREAD

**Issue by kenperkins** [usecanvas/canvas-cli#7]
I've created an account, and I love the idea of creating notes from the CLI, but I'm unable to login successfully from the CLI with 0.3.

I'm using a 1Password generated password that is 71 characters long, and I can successfully login on the website, but I only get errors through the command line:

``` bash
/Volumes/Data/src $ canvas login
Please enter your username or email: <mine>
Please enter your password:
Error:

/Volumes/Data/src $ canvas account
Please enter your username or email: <mine>
Please enter your password:
Error:
```

**Comment by chrmod** [comment]
got the same. also on linux my terminal sometimes stops printing user input after using cavas-cli

**Comment by kenperkins** [comment]
I tried to figure out what the client is doing (my go is not very good) but looking at:

https://github.com/usecanvas/canvas-cli/blob/master/client.go#L110-L113

It appears the route is `api.usecanvas.com/tokens`. I tried to curl it with a `POST` and got an invalid route error; My guess is the CLI is out of date with the current service.

**Comment by jclem** [comment]
Hey! This is actually an ooooooold CLI prototype built on top of our very first private API. I'm going to close this issue, but I would _really_ appreciate any thoughts either of you @kenperkins or @chrmod have on what you need from a CLI from us at jonathan@usecanvas.com

I'll also mark this repo as deprecated to prevent further confusion.
